config/routes.rb
Rails.application.routes.draw do
	
  post '/rate' => 'rater#create', :as => 'rate'
  resources :products
  namespace :admin do
    resources :users
    root to: "users#index"
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users
resources :favorite_products, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :watches
  has_many :watchers, :through => :watches

has_attached_file :image, styles: {carousel:"800x300#", main: "800x300^", min: "320x150#", thumb: "200x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  ratyrate_rateable 'product_rating'
  def self.search(search)
    where("name LIKE ? OR description LIKE ? OR category LIKE ? OR id LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
  end
  def self.comp(compare)
    where(id: compare)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
   
      
    @products = Product.all
    if params[:compare]
    	@products= Product.comp(params[:compare]).order("name DESC")
    else
    	if params[:search]
   		 @products = Product.search(params[:search]).order("name DESC")
  	else
    		@products = Product.all.order("name DESC")
  	end
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :picture, :category, :specs, :price, :product_id, :owner, :rating, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>

    <br><strong>Description</strong></br>
    <%= f.text_area(:description, size: "64x8") %>
    <br></br>
    
    <%= f.hidden_field :picture %>
    <%= f.input :category %>

    <br><strong>Specs</strong></br>
    <%= f.text_area(:specs, size: "64x8") %>
    <br></br>

    <%= f.input :price %>
    <%= f.hidden_field :product_id %>
    <%= f.hidden_field :owner %>
    <%= f.hidden_field :rating %>
    <%= f.input :image, as: :file%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Listing</h1>

<% if @products.present? %>
      <%=form_tag(products_path, method: :get)%>
      <%=submit_tag "Compare", :name => nil, :class=>"btn btn-info"%>
      <%if @products.size <= 3 %>
           <% @products.each_slice(3) do |products| %>
            <div class="row">
           
                 <% products.each do |product| %>
                 <div class="col-lg-2 product-container">
                 <%if product.image? %>
                     <%=link_to image_tag(product.image.url(:thumb)), product %></br>
                 <%end%>
                 <%= product.name %></br>
                 <%='Description: '%><%= simple_format(product.description)%></br>
                 <%='Price $ '%><%= product.price %></br>
                 <%='Select'%> <%=check_box_tag "compare[]", product.id%>  </br>
                 <%= rating_for product, "product_rating", disable_after_rate: true, imdb_avg: true %> </br>
                 <% if user_signed_in? %>
                 <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-sm btn-danger", :style=>'color:#FFFFFF;' %>
                   <%= link_to 'Edit', edit_product_path(product), :class=>"btn-sm btn-default" %>
                   <%= link_to 'Show', product, :class=>"btn-sm btn-default"%>
                 <% end %>
                 </div>
                 <%end%>
            </div>
           <%end%>
      <%else%>
           <% @products.each_slice(3) do |products| %>
            <div class="row">
               <% products.each do |product| %>
                   <div class="col-lg-2 product-container">
                      <%if product.image? %>
                      <%=link_to image_tag(product.image.url(:thumb)), product %></br>
                      <%end%>
                      <%= product.name %></br>
                      <%='$ '%><%= product.price %></br>
                      <%='Select'%> <%=check_box_tag "compare[]", product.id%>  </br>
                      <%= rating_for product, "product_rating", disable_after_rate: true, imdb_avg: true %> </br>
                      <% if user_signed_in? %>
                   <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-sm btn-danger x", :style=>'color:#FFFFFF;' %>
                   <%= link_to 'Edit', edit_product_path(product), :class=>"btn-sm btn-default" %>
                   <%= link_to 'Show', product, :class=>"btn-sm btn-default"%>
                   <% end %>
                   </div>
                 <% end %>
            </div>

   <%end%>
 <%end%>
  <br>
<%else%>  
  <h3>There are no products containing the term <%= params[:search] %>.</h3>
<% end %>
<% if user_signed_in? %>
  <%= link_to 'New Product', new_product_path, :class=>"btn btn-success", :style=>'color:#FFFFFF;' %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="modal-body row">
  <div class="col-md-6">
  <div class="product-image-container">
  <div class="product-image">
  <%if @product.image? %>
  
  <%= image_tag @product.image.url(:main) %>
    
  <% end %>
  </div>
  </div>
  </div>
  <div class="col-md-6">
    
    <div class="product-description-text">


 <h1><%= @product.name %></h1>
<div class="product-text">
<%= simple_format(@product.description) %>
</div>

<!-- <p>
  <strong>Picture:</strong>
  <%= @product.picture %>
</p> -->

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Specs:</strong>
  <%= simple_format(@product.specs) %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product.product_id %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @product.owner %>
</p>


<p>
  <strong>Overall Rating:</strong> 
  <%= rating_for @product, "product_rating", disable_after_rate: true, imdb_avg: true %>
</p>


<p>
  <% if current_user %>
    <strong>My Rating:</strong> 
    <%= rating_for_user @product, current_user, "product_rating" %>
  <% end %>
</p>

<% if current_user %>
  <%- unless current_user.favorite_products.exists?(id: @product.id) -%>
    <%= link_to 'Add to favorites', favorite_products_path(product_id: @product), method: :create, :class=>"btn-sm btn-info" %>
  <%- else -%>
    <%= link_to 'Remove from favorites', favorite_product_path(@product), method: :delete, :class=>"btn-sm btn-warning" %>
  <%- end -%>
    <!-- <%= link_to 'Edit', edit_product_path(@product) %> |  -->
    <%= link_to 'Back', products_path, :class=>"btn-sm btn-default" %>
<% end %>


</div>




  </div>
</div>







<!-- <p>
  <strong>Rating:</strong>
  <%= @product.rating %>
  <br>
</p> -->
<div class="row">
  <div class="small-2 large-4 columns">
      <br>
      <br>
  </div>
</div>